url: https://marialoni.org
baseurl: ""
quiet: true

exclude:
  - Rakefile
  - README.md
  - node_modules
  - package.json
  - package-lock.json

# See https://www.zotero.org/styles for more styles
scholar:
  source: .
  style: ./style/archiv-fur-geschichte-der-philosophie.csl
  sort_by: year
  order: descending
  bibliography_list_tag: ul
  repository: ./resources
  bibliography_template: linkitem
