name: Maria Aloni

highlighter: rouge
theme: minimal-mistakes-jekyll
url : "https://rednaw.github.io/" # 

scholar:
   source: .
   style: ./_scholar/simple-ieee.csl
   bibliography_list_tag: "ul.no-bullet"

