name: Maria Aloni

highlighter: rouge
url : https://rednaw.github.io/

# See https://www.zotero.org/styles for more styles
scholar:
   source: .
   style: ./style/archiv-fur-geschichte-der-philosophie.csl
   sort_by: year
   order: descending
   bibliography_list_tag: ul


