name: Maria Aloni

highlighter: rouge
url : https://rednaw.github.io/

# See https://www.zotero.org/styles for various styles
scholar:
   source: .
   style: ./_scholar/archiv-fur-geschichte-der-philosophie.csl
   #style: ./_scholar/informal-logic.csl


